using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;

namespace CS2MinecraftMapOptimizer
{
    // Minecraft block in the form of a func_breakable entity
    public class MCBlock
    {
        public string targetname; // Name automatically generated by us
        public Vector3 origin;
        public Vector3 angles;
        public Vector3 scales;

        // elementid of CMapEntity element
        public string id;

        // elementid of entity_properties element
        public string entity_properties_id;


        // -------------------------
        

        // Identifiers of a minecraft block's neighbors
        public enum Neighbor
        {
            POS_X = 0, // Neighbor in positive X direction
            POS_Y,     // Neighbor in positive Y direction
            POS_Z,     // etc.
            NEG_X,
            NEG_Y,
            NEG_Z
        }

        // Initialize this block as having no neighbors
        public MCBlock?[] neighbors = [null, null, null, null, null, null];


        // -------------------------


        // Whether this block needs to be hidden on round start
        public bool hiddenOnRoundStart = false;


        // -------------------------


        // OnBreak outputs of this block to be pasted into VMAP file.
        // When inserting this into the VMAP, remember to:
        // - Add proper indentation
        // - Add commas correctly, no trailing comma!
        // - Add line breaks
        public List<List<string>> onBreakOutputs = new List<List<string>>();
    }
}
